<style type="text/css">
    #ecw-query-input {
        background: #fff;
        border: 1px solid rgb(0, 181, 228);
        box-shadow: none;
        font-size: 18px;
        padding: 25px;
    }
    #ecw-btn-classify {
        background: rgb(0, 181, 228);
        padding: 25px;
        margin-left: 25px;
        border-radius: 5px;
    }
    .ecw-controls label {
        display: none;
    }
    .ecw-viz-bar {
        padding: 10px 5px 10px 5px;
        margin-bottom: 10px;
        font-size: 16px;
        color: white;
        text-shadow: 2px 2px 3px #333;
    }
    .ecw-viz-bar-pagedisplay {
        text-align: center;
        color: #ececec;
    }
    .ecw-viz-bar-pagedisplay-indicator.active {
        color: orange;
    }
    .btn-prev {
        float: left;
        color: orange;
        cursor: pointer;
    }
    .btn-next {
        float: right;
        color: orange;
        cursor: pointer;
    }
</style>

<div class="ecw-mask">
    <div class="ecw-loading-screen ecw-mask-asset">
        Loading...
        <div class="ecw-loading-spinner"></div>
    </div>
    <div class="ecw-dialog ecw-mask-asset">
        <div class="ecw-dialog-close">CLOSE</div>
        <span id="ecw-dialog-text">Dialog Text</span>
        <div><button class="ecw-button-dismiss" id="ecw-button-dismiss">Dismiss</button></div>
    </div>
    <div class="ecw-fullmodal ecw-mask-asset">
        <div class="ecw-fullmodal-close">CLOSE</div>
        <div class="ecw-fullmodal-content" id="ecw-tweets" v-if="category">
            <h5>Viewing Tweets mapped to {{ category.name }}</h5>
            <h7>{{ category.path.join(' :: ') }}</h7>
            <div class="tweet" v-for="tweet in category.tweets">
                <div class="avatar">
                    <img v-bind:src="tweet.user.profile_image_url">
                </div>
                <div class="tweet-content">
                    <div class="tweet-header">
                        <span class="name">{{ tweet.user.name }}</span><span class="screen-name">@{{ tweet.user.screen_name }}</span>
                    </div>
                    <div class="tweet-text">
                        {{ tweet.text }}
                    </div>
                    <div class="tweet-created-at">
                        {{ tweet.created_at }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="ecw-container">
    <div class="ecw-controls" id="chart-control">
        <label for="ecw-query-input" class="ecw-control-item">Enter a username or topic:</label>
        <input type="text" name="ecw-query-input" id="ecw-query-input" class="ecw-control-item" placeholder="Type here...." value="@reuters">
        <button id="ecw-btn-classify" class="ecw-control-item">Classify</button>
    </div>
    <?php if (!$this->app->session()->get('solved_captcha')): ?>
        <div class="g-recaptcha" data-sitekey="<?php echo getenv('GOOGLE_RECAPTCHA_SITEKEY'); ?>"></div>
    <?php endif; ?>
    <div id="ecw-chart-controls"></div>
    <div id="ecw-canvas"></div>
</div>

<script type="text/javascript" src="<?php echo $this->getDirUrl('js/widget-bar.js'); ?>"></script>