<style type="text/css">
    #ecw-query-input {
        background: #3e4b53;
        border: none !important;
        box-shadow: none;
        font-size: 18px;
        padding: 25px;
    }
    #ecw-btn-classify {
        background: rgb(0, 181, 228);
        padding: 25px;
        margin-left: 25px;
        border-radius: 5px;
    }
    .ecw-controls label {
        display: none;
    }
</style>

<div class="ecw-mask">
    <div class="ecw-loading-screen ecw-mask-asset">
        Loading...
        <div class="ecw-loading-spinner"></div>
    </div>
    <div class="ecw-dialog ecw-mask-asset">
        <div class="ecw-dialog-close">CLOSE</div>
        <span id="ecw-dialog-text">Dialog Text</span>
        <div><button class="ecw-button-dismiss" id="ecw-button-dismiss">Dismiss</button></div>
    </div>
</div>

<div class="ecw-container">
    <div class="ecw-controls">
        <label for="ecw-query-input" class="ecw-control-item">Enter a username or topic:</label>
        <input type="text" name="ecw-query-input" id="ecw-query-input" class="ecw-control-item" value="Type here....">
        <button id="ecw-btn-classify" class="ecw-control-item">Classify</button>
    </div>
    <?php if (!$this->app->session()->get('solved_captcha')): ?>
        <div class="g-recaptcha" data-sitekey="<?php echo getenv('GOOGLE_RECAPTCHA_SITEKEY'); ?>"></div>
    <?php endif; ?>
    <div id="ecw-chart-controls"></div>
    <div id="ecw-canvas"></div>
</div>

<script type="text/javascript" src="<?php echo $this->getDirUrl('js/widget-bar.js'); ?>"></script>